### ISSUE TITLE
Listing lights fail

### ISSUE THREAD

**Issue by VoyagerMP** [birkirb/hue-cli#10]
root@fw:~ => vi /usr/local/lib/ruby/gems/2.4/gems/hue-lib-0.7.4/lib/hue/bulb.rb +92
root@fw:~ => hue24 lights
1.  Stehlampe Esszimmer: OFF
    Brightness: 0 (0%)
    Color: XY=[0.4578, 0.41], RGB≈[227, 172, 104]
2.  Stehlampe Wohnzimmer: OFF
    Brightness: 152 (60%)
    Color: Temperature=2732°K (366 mired), RGB≈[255, 166, 87]
3.  Stehlampe: ON
    Brightness: 254 (100%)
    Color: Temperature=2732°K (366 mired), RGB≈[255, 166, 87]
5.  Tisch: OFF
    Brightness: 192 (75%)
    Color: XY=[0.4174, 0.33], RGB≈[233, 140, 161]
6.  Lampe: OFF
    Brightness: 0 (0%)
    Effect:
7.  Stehlampe Schlafzimmer: OFF
    Brightness: 0 (0%)
    Effect:
10. Deckenleuchte links: ON
    Brightness: 254 (100%)
    Effect:
11. Deckenleuchte rechts: ON
    Brightness: 254 (100%)
    Effect:
14. Deckenleuchte Wohnzimmer 1: ON
    Brightness: 254 (100%)
    Effect:
15. Deckenleuchte Flur 1: OFF
    Brightness: 126 (49%)
    Effect:
16. Deckenleuchte Flur 2: OFF
    Brightness: 126 (49%)
    Effect:
17. Deckenleuchte Wohnzimmer 2: ON
    Brightness: 254 (100%)
    Effect:
18. Deckenleucht Schlafzimmer: ON
    Brightness: 254 (100%)
    Effect:
19. Dusche2: ON
    Brightness: 254 (100%)
    Color: Temperature=2732°K (366 mired), RGB≈[255, 166, 87]
20. Dusche1: ON
    Brightness: 254 (100%)
    Color: Temperature=2732°K (366 mired), RGB≈[255, 166, 87]
21. Links: OFF
    Brightness: 126 (49%)
    Color: XY=[0.4575, 0.4099], RGB≈[227, 172, 104]
22. Rechts: OFF
    Brightness: 126 (49%)
    Color: XY=[0.4575, 0.4099], RGB≈[227, 172, 104]
23. Steckdose: OFF
/usr/local/lib/ruby/gems/2.4/gems/hue-lib-0.7.4/lib/hue/bulb.rb:92:in `brightness_in_unit_interval': undefined method `/' for nil:NilClass (NoMethodError)
        from /usr/local/lib/ruby/gems/2.4/gems/hue-lib-0.7.4/lib/hue/bulb.rb:96:in `brightness_percent'
        from /usr/local/lib/ruby/gems/2.4/gems/hue-cli-0.1.4/lib/hue/extensions/bulb.rb:11:in `block in print_state'
        from /usr/local/lib/ruby/gems/2.4/gems/hue-cli-0.1.4/lib/utilities/indentation.rb:11:in `indent'
        from /usr/local/lib/ruby/gems/2.4/gems/hue-cli-0.1.4/lib/hue/extensions/bulb.rb:10:in `print_state'
        from /usr/local/lib/ruby/gems/2.4/gems/hue-cli-0.1.4/lib/hue/extensions/bridge.rb:48:in `block in print_bulbs'
        from /usr/local/lib/ruby/gems/2.4/gems/hue-cli-0.1.4/lib/hue/extensions/bridge.rb:47:in `each'
        from /usr/local/lib/ruby/gems/2.4/gems/hue-cli-0.1.4/lib/hue/extensions/bridge.rb:47:in `print_bulbs'
        from /usr/local/lib/ruby/gems/2.4/gems/hue-cli-0.1.4/lib/hue/cli/commands/lights.rb:16:in `execute'
        from /usr/local/lib/ruby/gems/2.4/gems/hue-cli-0.1.4/lib/hue/cli.rb:30:in `run'
        from /usr/local/lib/ruby/gems/2.4/gems/hue-cli-0.1.4/bin/hue:5:in `<top (required)>'
        from /usr/local/bin/hue24:23:in `load'
        from /usr/local/bin/hue24:23:in `<main>'

**Comment by majick** [comment]
I fixed this in https://github.com/birkirb/hue-cli/pull/12 but I think the maintainer is no longer active.
